#!/usr/bin/env bash
#
# Regenerate resources/render/draftsman-render.css from frontv's built CSS.
#
#   scripts/sync-render-css.sh [path-to-frontv]
#
# Copies the compiled stylesheet (Tailwind + AlpineFlow structural CSS +
# frontv's alpineflow-theme.css) and inlines every root-relative SVG the CSS
# references (row markers, header toggler glyphs) as data: URIs, so the static
# graph render page is fully self-contained. Run after any frontv `npm run
# build` whose CSS changes; goes away once the full frontv build ships inside
# this package.

set -euo pipefail

FRONTV="${1:-$(dirname "$0")/../../frontv}"
OUT="$(dirname "$0")/../resources/render/draftsman-render.css"

CSS_FILE=$(ls "$FRONTV"/dist/assets/*.css 2>/dev/null | head -1)
[ -n "$CSS_FILE" ] || { echo "no built CSS in $FRONTV/dist/assets — run npm run build there first" >&2; exit 1; }

FRONTV="$FRONTV" CSS_FILE="$CSS_FILE" OUT="$OUT" python3 << 'PY'
import base64
import os
import re

frontv = os.environ["FRONTV"]
css = open(os.environ["CSS_FILE"]).read()

def inline(match):
    path = match.group(1)
    file = os.path.join(frontv, "public", path.lstrip("/"))
    if not os.path.exists(file) or not path.endswith(".svg"):
        return match.group(0)
    data = base64.b64encode(open(file, "rb").read()).decode()
    return f"url(data:image/svg+xml;base64,{data})"

css = re.sub(r"url\((?:'|\")?(/[^)'\"]+)(?:'|\")?\)", inline, css)

header = (
    "/* draftsman-render.css — BUILD ARTIFACT, do not hand-edit.\n"
    "   Generated by scripts/sync-render-css.sh from frontv's built CSS, with\n"
    "   the root-relative SVG assets inlined as data: URIs. Regenerate after\n"
    "   any frontv build whose CSS changes. */\n"
)
open(os.environ["OUT"], "w").write(header + css)
print(f"wrote {os.environ['OUT']} ({len(css)} bytes of CSS)")
PY
